# PART A â€“ Regression modelling for business decision making

In [2]:
# Importing necessary libraries
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import RobustScaler

In [ ]:
# Loading the dataset. The dataset is uploaded in the GoogleCollab.
df = pd.read_csv('House_price.csv')

# Task-1 Data Preprocessing

a) Properly clean the dataset, handle any missing values, and remove outliers

In [ ]:
# Display the first few rows of the dataset
df.head()

,Avg. Area Income,House Age,Number of Rooms,Number of Bedrooms,Area Population,Price,Address
0,79545.45857,5.682861,7.009188,4.09,23086.80050,1.059034e+06,"208 Michael Ferry Apt. 674\nLaurabury, NE 3701..."
1,79248.64245,6.002900,6.730821,3.09,40173.07217,1.505891e+06,"188 Johnson Views Suite 079\nLake Kathleen, CA..."
2,61287.06718,5.865890,8.512727,5.13,36882.15940,1.058988e+06,"9127 Elizabeth Stravenue\nDanieltown, WI 06482..."
3,63345.24005,7.188236,5.586729,3.26,34310.24283,1.260617e+06,USS Barnett\nFPO AP 44820
4,59982.19723,5.040555,7.839388,4.23,26354.10947,6.309435e+05,USNS Raymond\nFPO AE 09386

In [ ]:
# Structure of the dataset
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4548 entries, 0 to 4547
Data columns (total 7 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Avg. Area Income    4548 non-null   float64
 1   House Age           4548 non-null   float64
 2   Number of Rooms     4548 non-null   float64
 3   Number of Bedrooms  4548 non-null   float64
 4   Area Population     4548 non-null   float64
 5   Price               4548 non-null   float64
 6   Address             4548 non-null   object
dtypes: float64(6), object(1)
memory usage: 248.8+ KB

In [ ]:
# Descriptive statistics for the dataset
df.describe()

,Avg. Area Income,House Age,Number of Rooms,Number of Bedrooms,Area Population,Price
count,4548.000000,4548.000000,4548.000000,4548.000000,4548.000000,4.548000e+03
mean,68611.700818,5.978918,6.987646,3.981693,36187.469334,1.233916e+06
std,10686.487761,0.990850,1.006587,1.230939,9910.189915,3.545676e+05
min,17796.631190,2.644304,3.236194,2.000000,172.610686,1.593866e+04
25%,61485.150192,5.332187,6.299692,3.140000,29423.163510,9.977751e+05
50%,68817.036575,5.960872,7.002245,4.050000,36215.560985,1.234571e+06
75%,75820.741747,6.658368,7.665871,4.490000,42880.554642,1.470616e+06
max,107701.748400,9.519088,10.759588,6.500000,69592.040240,2.469066e+06

In [ ]:
# Display missing values in the dataset
missing_values = df.isnull().sum()
print("Missing values in each column:\n", missing_values)

Missing values in each column:
 Avg. Area Income      0
House Age             0
Number of Rooms       0
Number of Bedrooms    0
Area Population       0
Price                 0
Address               0
dtype: int64

In [ ]:
import matplotlib.pyplot as plt

In [ ]:
# Removing the outliers from the dataset
def remove_outliers(df, column):
    Q1 = df[column].quantile(0.25)
    Q3 = df[column].quantile(0.75)
    IQR = Q3 - Q1
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR
    return df[(df[column] >= lower_bound) & (df[column] <= upper_bound)]

In [ ]:
# Applying the function to relevant numerical columns
for column in df.select_dtypes(include=['float64', 'int64']).columns:
    df = remove_outliers(df, column)

In [ ]:
# Verify the changes
df.describe()

,Avg. Area Income,House Age,Number of Rooms,Number of Bedrooms,Area Population,Price
count,4415.000000,4415.000000,4415.000000,4415.000000,4415.000000,4.415000e+03
mean,68625.562010,5.977806,6.987266,3.984598,36159.676459,1.233401e+06
std,10306.583987,0.964864,0.983385,1.231457,9612.957623,3.377393e+05
min,40141.566480,3.342599,4.290699,2.000000,9487.921585,3.023074e+05
25%,61601.809360,5.338686,6.308265,3.150000,29498.467740,1.003740e+06
50%,68854.090850,5.959945,7.002164,4.050000,36183.287800,1.234037e+06
75%,75732.554225,6.647182,7.661763,4.490000,42771.784635,1.464820e+06
max,97112.361250,8.641821,9.710217,6.500000,62963.755390,2.152959e+06

In [ ]:
from sklearn.preprocessing import StandardScaler

In [ ]:
# Initialize the scaler
scaler = StandardScaler()

In [ ]:
# Apply scaling to numerical columns
df[df.select_dtypes(include=['float64', 'int64']).columns] = scaler.fit_transform(df.select_dtypes(include=['float64', 'int64']).values)

In [ ]:
# Verify the scaling
df.describe()

,Avg. Area Income,House Age,Number of Rooms,Number of Bedrooms,Area Population,Price
count,4.415000e+03,4.415000e+03,4.415000e+03,4.415000e+03,4.415000e+03,4.415000e+03
mean,-7.725040e-17,1.722040e-16,-6.920348e-17,7.503750e-17,-5.825968e-16,4.828150e-17
std,1.000113e+00,1.000113e+00,1.000113e+00,1.000113e+00,1.000113e+00,1.000113e+00
min,-2.763983e+00,-2.731478e+00,-2.742437e+00,-1.611767e+00,-2.774877e+00,-2.757153e+00
25%,-6.815593e-01,-6.624690e-01,-6.905519e-01,-6.778087e-01,-6.930191e-01,-6.800709e-01
50%,2.217560e-02,-1.851424e-02,1.515110e-02,5.311548e-02,2.456478e-03,1.884563e-03
75%,6.896366e-01,6.938296e-01,6.859703e-01,4.104562e-01,6.879108e-01,6.852773e-01
max,2.764255e+00,2.761338e+00,2.769270e+00,2.042854e+00,2.788644e+00,2.722996e+00

In [ ]:
# Perform one-hot encoding on categorical columns
df = pd.get_dummies(df, drop_first=True)

In [ ]:
# Verify the encoding
df.head()

,Avg. Area Income,House Age,Number of Rooms,Number of Bedrooms,Area Population,Price,"Address_000 Todd Pines\nAshleyberg, KY 90207-1179","Address_001 Steve Plaza\nJessicastad, UT 25190","Address_0010 Gregory Loaf\nSouth Ericfort, VA 34651-0718","Address_00149 Raymond Knolls\nNew Jason, UT 75026",...,Address_Unit 9446 Box 0958\nDPO AE 97025,Address_Unit 9463 Box 0963\nDPO AE 49984-2796,Address_Unit 9494 Box 2307\nDPO AE 58622,Address_Unit 9664 Box 1605\nDPO AA 30902,Address_Unit 9732 Box 1846\nDPO AE 69898-3304,Address_Unit 9774 Box 4511\nDPO AE 44963,Address_Unit 9778 Box 2114\nDPO AP 59374,Address_Unit 9785 Box 0790\nDPO AP 60371-0797,Address_Unit 9831 Box 7128\nDPO AA 54705,Address_Unit 9871 Box 9037\nDPO AP 37275-9289
0,1.059627,-0.305720,0.022295,0.085601,-1.360076,-0.516336,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,1.030825,0.026010,-0.260808,-0.726537,0.417546,0.806897,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,-0.712101,-0.116005,1.551410,0.930225,0.075166,-0.516471,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,-0.512383,1.254650,-1.424362,-0.588474,-0.192411,0.080592,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,-0.838721,-0.971492,0.866617,0.199300,-1.020152,-1.783996,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
# Target variable is 'Price'
X = df.drop('Price', axis=1)
y = df['Price']

# Split the data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Verify the split
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((3532, 4419), (883, 4419), (3532,), (883,))

In [ ]:
from sklearn.linear_model import Ridge
from sklearn.model_selection import GridSearchCV

In [ ]:
# Initialize the model
ridge = Ridge()

In [ ]:
# Define the hyperparameters grid
param_grid = {
    'alpha': [0.1, 1.0, 10.0, 100.0],
    'solver': ['auto', 'svd', 'cholesky', 'lsqr']
}

In [ ]:
# Initialize GridSearchCV
grid_search = GridSearchCV(ridge, param_grid, cv=5, scoring='neg_mean_absolute_error')

In [ ]:
# Fit the grid search
grid_search.fit(X_train, y_train)

GridSearchCV(cv=5, estimator=Ridge(),
             param_grid={'alpha': [0.1, 1.0, 10.0, 100.0],
                         'solver': ['auto', 'svd', 'cholesky', 'lsqr']},
             scoring='neg_mean_absolute_error')

In [ ]:
# Print the best parameters and the best score
best_params = grid_search.best_params_
best_score = grid_search.best_score_
print("Best Parameters:", best_params)
print("Best Score:", best_score)

NameError: name 'grid_search' is not defined

In [ ]:
import pandas as pd

In [ ]:
# Loading the dataset
df1 = pd.read_csv('income.csv')

In [ ]:
# Display the first few rows and summary statistics
print(df1.head())
print(df1.info())
print(df1.describe(include='all'))

   age       JobType         EdType        maritalstatus       occupation  \
0   45       Private        HS-grad             Divorced     Adm-clerical
1   24   Federal-gov        HS-grad        Never-married     Armed-Forces
2   44       Private   Some-college   Married-civ-spouse   Prof-specialty
3   27       Private            9th        Never-married     Craft-repair
4   20       Private   Some-college        Never-married            Sales

      relationship    race   gender  capitalgain  capitalloss  hoursperweek  \
0    Not-in-family   White   Female            0            0            28
1        Own-child   White     Male            0            0            40
2          Husband   White     Male            0            0            40
3   Other-relative   White     Male            0            0            40
4    Not-in-family   White     Male            0            0            35

    nativecountry                        SalStat
0   United-States   less than or equal to 50,000
1   United-States   less than or equal to 50,000
2   United-States            greater than 50,000
3          Mexico   less than or equal to 50,000
4   United-States   less than or equal to 50,000
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 31978 entries, 0 to 31977
Data columns (total 13 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   age            31978 non-null  int64
 1   JobType        31978 non-null  object
 2   EdType         31978 non-null  object
 3   maritalstatus  31978 non-null  object
 4   occupation     31978 non-null  object
 5   relationship   31978 non-null  object
 6   race           31978 non-null  object
 7   gender         31978 non-null  object
 8   capitalgain    31978 non-null  int64
 9   capitalloss    31978 non-null  int64
 10  hoursperweek   31978 non-null  int64
 11  nativecountry  31978 non-null  object
 12  SalStat        31978 non-null  object
dtypes: int64(4), object(9)
memory usage: 3.2+ MB
None
                 age   JobType    EdType        maritalstatus  \
count   31978.000000     31978     31978                31978
unique           NaN         9        16                    7
top              NaN   Private   HS-grad   Married-civ-spouse
freq             NaN     22286     10368                14692
mean       38.579023       NaN       NaN                  NaN
std        13.662085       NaN       NaN                  NaN
min        17.000000       NaN       NaN                  NaN
25%        28.000000       NaN       NaN                  NaN
50%        37.000000       NaN       NaN                  NaN
75%        48.000000       NaN       NaN                  NaN
max        90.000000       NaN       NaN                  NaN

             occupation relationship    race gender   capitalgain  \
count             31978        31978   31978  31978  31978.000000
unique               15            6       5      2           NaN
top      Prof-specialty      Husband   White   Male           NaN
freq               4038        12947   27430  21370           NaN
mean                NaN          NaN     NaN    NaN   1064.360623
std                 NaN          NaN     NaN    NaN   7298.596271
min                 NaN          NaN     NaN    NaN      0.000000
25%                 NaN          NaN     NaN    NaN      0.000000
50%                 NaN          NaN     NaN    NaN      0.000000
75%                 NaN          NaN     NaN    NaN      0.000000
max                 NaN          NaN     NaN    NaN  99999.000000

         capitalloss  hoursperweek   nativecountry  \
count   31978.000000  31978.000000           31978
unique           NaN           NaN              41
top              NaN           NaN   United-States
freq             NaN           NaN           29170
mean       86.739352     40.417850             NaN
std       401.594301     12.345285             NaN
min         0.000000      1.000000             NaN
25%         0.000000     40.000000             NaN
50%         0.000000     40.000000             NaN
75%         0.000000     45.000000             NaN
max      4356.000000     99.000000             NaN

                              SalStat
count                           31978
unique                              2
top      less than or equal to 50,000
freq                            24283
mean                              NaN
std                               NaN
min                               NaN
25%                               NaN
50%                               NaN
75%                               NaN
max                               NaN

In [ ]:
# Checking for missing values
missing_values = df1.isnull().sum()
print("Missing values in each column:\n", missing_values)

Missing values in each column:
 age              0
JobType          0
EdType           0
maritalstatus    0
occupation       0
relationship     0
race             0
gender           0
capitalgain      0
capitalloss      0
hoursperweek     0
nativecountry    0
SalStat          0
dtype: int64

In [ ]:
def remove_outliers_using_iqr(df1, column):
    Q1 = df1[column].quantile(0.25)
    Q3 = df1[column].quantile(0.75)
    IQR = Q3 - Q1
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR

    # Use df1[column] for the boolean indexing to ensure alignment
    return df1[(df1[column] >= lower_bound) & (df1[column] <= upper_bound)]

# Apply the function to relevant numerical columns
numerical_columns = df1.select_dtypes(include=['float64', 'int64']).columns
for column in numerical_columns:
    df1 = remove_outliers_using_iqr(df1, column)

# Verify the changes
print(df1.describe())

                age  capitalgain  capitalloss  hoursperweek
count  13149.000000      13149.0      13149.0       13149.0
mean      37.923112          0.0          0.0          40.0
std       12.258415          0.0          0.0           0.0
min       17.000000          0.0          0.0          40.0
25%       28.000000          0.0          0.0          40.0
50%       36.000000          0.0          0.0          40.0
75%       47.000000          0.0          0.0          40.0
max       75.000000          0.0          0.0          40.0

In [ ]:
from sklearn.preprocessing import StandardScaler

# Initialize the scaler
scaler = StandardScaler()

# Apply scaling to numerical columns
df1[numerical_columns] = scaler.fit_transform(df1[numerical_columns])

# Verify the scaling
print(df1.describe)

<bound method NDFrame.describe of             age       JobType         EdType        maritalstatus  \
1     -1.135844   Federal-gov        HS-grad        Never-married
2      0.495751       Private   Some-college   Married-civ-spouse
3     -0.891104       Private            9th        Never-married
5      0.495751       Private        HS-grad              Widowed
6      1.066809       Private        HS-grad   Married-civ-spouse
...         ...           ...            ...                  ...
31968 -1.706902             ?           11th        Never-married
31974 -0.320046     Local-gov   Some-college        Never-married
31975 -1.217423       Private   Some-college   Married-civ-spouse
31976  0.332591     Local-gov   Some-college   Married-civ-spouse
31977 -0.727945       Private      Bachelors        Never-married

             occupation     relationship                 race   gender  \
1          Armed-Forces        Own-child                White     Male
2        Prof-specialty          Husband                White     Male
3          Craft-repair   Other-relative                White     Male
5       Exec-managerial        Unmarried                Black   Female
6          Craft-repair          Husband   Amer-Indian-Eskimo     Male
...                 ...              ...                  ...      ...
31968                 ?        Own-child                White     Male
31974   Protective-serv    Not-in-family                White   Female
31975      Adm-clerical          Husband                White     Male
31976      Adm-clerical             Wife                White   Female
31977    Prof-specialty    Not-in-family                White     Male

       capitalgain  capitalloss  hoursperweek   nativecountry  \
1              0.0          0.0           0.0   United-States
2              0.0          0.0           0.0   United-States
3              0.0          0.0           0.0          Mexico
5              0.0          0.0           0.0   United-States
6              0.0          0.0           0.0   United-States
...            ...          ...           ...             ...
31968          0.0          0.0           0.0   United-States
31974          0.0          0.0           0.0   United-States
31975          0.0          0.0           0.0   United-States
31976          0.0          0.0           0.0   United-States
31977          0.0          0.0           0.0   United-States

                             SalStat
1       less than or equal to 50,000
2                greater than 50,000
3       less than or equal to 50,000
5       less than or equal to 50,000
6       less than or equal to 50,000
...                              ...
31968   less than or equal to 50,000
31974   less than or equal to 50,000
31975   less than or equal to 50,000
31976   less than or equal to 50,000
31977   less than or equal to 50,000

[13149 rows x 13 columns]>

In [ ]:
# Perform one-hot encoding on categorical columns
df1 = pd.get_dummies(df1, drop_first=True)

# Verify the encoding
print(df1.head())

        age  capitalgain  capitalloss  hoursperweek  JobType_ Federal-gov  \
1 -1.135844          0.0          0.0           0.0                  True
2  0.495751          0.0          0.0           0.0                 False
3 -0.891104          0.0          0.0           0.0                 False
5  0.495751          0.0          0.0           0.0                 False
6  1.066809          0.0          0.0           0.0                 False

   JobType_ Local-gov  JobType_ Never-worked  JobType_ Private  \
1               False                  False             False
2               False                  False              True
3               False                  False              True
5               False                  False              True
6               False                  False              True

   JobType_ Self-emp-inc  JobType_ Self-emp-not-inc  ...  \
1                  False                      False  ...
2                  False                      False  ...
3                  False                      False  ...
5                  False                      False  ...
6                  False                      False  ...

   nativecountry_ Puerto-Rico  nativecountry_ Scotland  nativecountry_ South  \
1                       False                    False                 False
2                       False                    False                 False
3                       False                    False                 False
5                       False                    False                 False
6                       False                    False                 False

   nativecountry_ Taiwan  nativecountry_ Thailand  \
1                  False                    False
2                  False                    False
3                  False                    False
5                  False                    False
6                  False                    False

   nativecountry_ Trinadad&Tobago  nativecountry_ United-States  \
1                           False                          True
2                           False                          True
3                           False                         False
5                           False                          True
6                           False                          True

   nativecountry_ Vietnam  nativecountry_ Yugoslavia  \
1                   False                      False
2                   False                      False
3                   False                      False
5                   False                      False
6                   False                      False

   SalStat_ less than or equal to 50,000
1                                   True
2                                  False
3                                   True
5                                   True
6                                   True

[5 rows x 97 columns]

In [ ]:
from sklearn.model_selection import train_test_split

# Target variable is the last column and is categorical
X = df1.drop(df1.columns[-1], axis=1)
y = df1[df1.columns[-1]]

# Split the data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Verify the split
print(X_train.shape, X_test.shape, y_train.shape, y_test.shape)

(10519, 96) (2630, 96) (10519,) (2630,)

In [ ]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import GridSearchCV

In [ ]:
# Initialize the model
rf = RandomForestClassifier(random_state=42)

# Define the hyperparameters grid
param_grid = {
    'n_estimators': [100, 200, 300],
    'max_depth': [10, 20, 30, None],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 2, 4]
}

In [ ]:
# Initialize GridSearchCV
grid_search = GridSearchCV(rf, param_grid, cv=5, scoring='accuracy')

In [ ]:
# Fit the grid search
grid_search.fit(X_train, y_train)

GridSearchCV(cv=5, estimator=RandomForestClassifier(random_state=42),
             param_grid={'max_depth': [10, 20, 30, None],
                         'min_samples_leaf': [1, 2, 4],
                         'min_samples_split': [2, 5, 10],
                         'n_estimators': [100, 200, 300]},
             scoring='accuracy')

In [ ]:
# Print the best parameters and the best score
best_params = grid_search.best_params_
best_score = grid_search.best_score_
print("Best Parameters:", best_params)
print("Best Score:", best_score)

Best Parameters: {'max_depth': None, 'min_samples_leaf': 2, 'min_samples_split': 10, 'n_estimators': 200}
Best Score: 0.8608235745060921

In [ ]:
# Build the final model with the best parameters
rf_best = RandomForestClassifier(**best_params, random_state=42)
rf_best.fit(X_train, y_train)

# Verify model performance on the training set
print(rf_best.score(X_train, y_train))

0.8842095256203061